import type { Metadata } from "next";
import "./globals.css";

import Header from "./components/header";
import Footer from "./components/footer";

import { Manrope } from 'next/font/google'
import SubFooter from "./components/subFooter";

// If loading a variable font, you don't need to specify the font weight
const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.className}
      >
        <div className="mx-auto">
          <Header/>
          {children}
          <SubFooter/>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
